In [3]:
from numpy import array 
T = array([ [[23,50], [7,12]], [[57,67], [99,43]], [[75,21], [57,12]], [[87,26],[18,84]] ]) 
print(T.shape)
print(T)

(4, 2, 2)
[[[23 50]
  [ 7 12]]

 [[57 67]
  [99 43]]

 [[75 21]
  [57 12]]

 [[87 26]
  [18 84]]]


In [6]:
a = array([[23, 50, 19], [7, 12, 109], [57, 67, 98]]) 
b = array([17, 22, 19])
c = a * b
print(c)

[[ 391 1100  361]
 [ 119  264 2071]
 [ 969 1474 1862]]


In [7]:
x = array([[23, 50, 19], [7, 12, 109], [57, 67, 98]]) 
y = x.T 
print(y)

[[ 23   7  57]
 [ 50  12  67]
 [ 19 109  98]]
